"""change controller table3

Revision ID: 0243f258ffdc
Revises: 3a1d91de86da
Create Date: 2026-05-27 21:01:42.096097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0243f258ffdc'
down_revision: Union[str, Sequence[str], None] = '3a1d91de86da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('is_automatic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller', 'is_automatic')
    # ### end Alembic commands ###
