"""update trigger model

Revision ID: 0acc6752aa22
Revises: bc202e4e49bf
Create Date: 2026-05-27 14:58:14.556767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acc6752aa22'
down_revision: Union[str, Sequence[str], None] = 'bc202e4e49bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trigger', 'last_value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trigger', 'notif_value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('trigger_controller_id_fkey'), 'trigger', type_='foreignkey')
    op.drop_column('trigger', 'controller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trigger', sa.Column('controller_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('trigger_controller_id_fkey'), 'trigger', 'controller', ['controller_id'], ['id'])
    op.alter_column('trigger', 'notif_value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('trigger', 'last_value',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
