"""change controller table2

Revision ID: 3a1d91de86da
Revises: ebb68699b397
Create Date: 2026-05-27 17:58:46.352151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1d91de86da'
down_revision: Union[str, Sequence[str], None] = 'ebb68699b397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('trigger_vector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller', 'trigger_vector')
    # ### end Alembic commands ###
