"""change controller and trigger tables, dump data tables

Revision ID: 42d427dc6a0e
Revises: 0243f258ffdc
Create Date: 2026-05-28 13:57:08.614874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42d427dc6a0e'
down_revision: Union[str, Sequence[str], None] = '0243f258ffdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controller_data')
    op.drop_table('trigger_data')
    op.add_column('controller', sa.Column('pin', sa.Integer(), nullable=False))
    op.add_column('trigger', sa.Column('type', sa.String(), nullable=True))
    op.add_column('trigger', sa.Column('pin', sa.Integer(), nullable=False))
    op.drop_column('trigger', 'write_clock')
    op.drop_column('trigger', 'check_clock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trigger', sa.Column('check_clock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trigger', sa.Column('write_clock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trigger', 'pin')
    op.drop_column('trigger', 'type')
    op.drop_column('controller', 'pin')
    op.create_table('trigger_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trigger_data_pkey'))
    )
    op.create_table('controller_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('controller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('controller_data_pkey'))
    )
    # ### end Alembic commands ###
