"""change controller table

Revision ID: ebb68699b397
Revises: 0acc6752aa22
Create Date: 2026-05-27 17:43:05.667705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb68699b397'
down_revision: Union[str, Sequence[str], None] = '0acc6752aa22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('trigger_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'controller', 'trigger', ['trigger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'controller', type_='foreignkey')
    op.drop_column('controller', 'trigger_id')
    # ### end Alembic commands ###
